<a href="https://colab.research.google.com/github/polugariteja/2311cs020531/blob/main/Decission_Tree_With_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
file_name = '/content/iris.csv'

In [26]:
import pandas as pd
iris=pd.read_csv(file_name)

In [27]:
iris

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0             1           5.1          3.5           1.4          0.2   
1             2           4.9          3.0           1.4          0.2   
2             3           4.7          3.2           1.3          0.2   
3             4           4.6          3.1           1.5          0.2   
4             5           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         146           6.7          3.0           5.2          2.3   
146         147           6.3          2.5           5.0          1.9   
147         148           6.5          3.0           5.2          2.0   
148         149           6.2          3.4           5.4          2.3   
149         150           5.9          3.0           5.1          1.8   

       Species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 6 columns]

In [20]:
iris.shape

(150, 6)

In [21]:
 label_encoder = preprocessing.LabelEncoder()
 iris['Species']= label_encoder.fit_transform(iris['Species'])
 iris['Species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [22]:
iris

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             1           5.1          3.5           1.4          0.2        0
1             2           4.9          3.0           1.4          0.2        0
2             3           4.7          3.2           1.3          0.2        0
3             4           4.6          3.1           1.5          0.2        0
4             5           5.0          3.6           1.4          0.2        0
..          ...           ...          ...           ...          ...      ...
145         146           6.7          3.0           5.2          2.3        2
146         147           6.3          2.5           5.0          1.9        2
147         148           6.5          3.0           5.2          2.0        2
148         149           6.2          3.4           5.4          2.3        2
149         150           5.9          3.0           5.1          1.8        2

[150 rows x 6 columns]

In [23]:
iris['Petal.Length'].unique()
iris['Sepal.Length'].unique()
iris['Sepal.Width'].unique()
iris['Petal.Width'].unique()
iris['Species'].unique()

array([0, 1, 2])

In [24]:
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           1           5.1          3.5           1.4          0.2        0
1           2           4.9          3.0           1.4          0.2        0
2           3           4.7          3.2           1.3          0.2        0
3           4           4.6          3.1           1.5          0.2        0
4           5           5.0          3.6           1.4          0.2        0

In [28]:
iris=pd.read_csv('/content/iris.csv',index_col=0)

In [29]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [30]:
iris=iris.rename(columns={"Species":"Flowers_Type"})

In [31]:
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Flowers_Type
1             5.1          3.5           1.4          0.2       setosa
2             4.9          3.0           1.4          0.2       setosa
3             4.7          3.2           1.3          0.2       setosa
4             4.6          3.1           1.5          0.2       setosa
5             5.0          3.6           1.4          0.2       setosa
..            ...          ...           ...          ...          ...
146           6.7          3.0           5.2          2.3    virginica
147           6.3          2.5           5.0          1.9    virginica
148           6.5          3.0           5.2          2.0    virginica
149           6.2          3.4           5.4          2.3    virginica
150           5.9          3.0           5.1          1.8    virginica

[150 rows x 5 columns]

In [34]:
 label_encoder = preprocessing.LabelEncoder()
 iris['Flowers_Type']= label_encoder.fit_transform(iris['Flowers_Type'])
 iris['Flowers_Type']

1      0
2      0
3      0
4      0
5      0
      ..
146    2
147    2
148    2
149    2
150    2
Name: Flowers_Type, Length: 150, dtype: int64

In [36]:
x

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Flowers_Type
1             5.1          3.5           1.4          0.2             0
2             4.9          3.0           1.4          0.2             0
3             4.7          3.2           1.3          0.2             0
4             4.6          3.1           1.5          0.2             0
5             5.0          3.6           1.4          0.2             0
..            ...          ...           ...          ...           ...
146           6.7          3.0           5.2          2.3             2
147           6.3          2.5           5.0          1.9             2
148           6.5          3.0           5.2          2.0             2
149           6.2          3.4           5.4          2.3             2
150           5.9          3.0           5.1          1.8             2

[150 rows x 5 columns]

In [42]:
y=iris.iloc[:, 4]
y

1      0
2      0
3      0
4      0
5      0
      ..
146    2
147    2
148    2
149    2
150    2
Name: Flowers_Type, Length: 150, dtype: int64

In [37]:
x=iris.iloc[:, 0:4]
x

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
1             5.1          3.5           1.4          0.2
2             4.9          3.0           1.4          0.2
3             4.7          3.2           1.3          0.2
4             4.6          3.1           1.5          0.2
5             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
146           6.7          3.0           5.2          2.3
147           6.3          2.5           5.0          1.9
148           6.5          3.0           5.2          2.0
149           6.2          3.4           5.4          2.3
150           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [38]:
iris['Flowers_Type'].unique()

array([0, 1, 2])

In [54]:
iris['Flowers_Type'].value_counts()

Flowers_Type
0    50
1    50
2    50
Name: count, dtype: int64

In [39]:
columns=list(iris.columns)
columns

['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Flowers_Type']

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [44]:
from sklearn.tree import DecisionTreeClassifier
model_gini=DecisionTreeClassifier(criterion='gini',max_depth=3)

In [45]:
model_gini.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [46]:
preds=model_gini.predict(x_test)
print(preds)
pd.Series(preds).value_counts()

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 1 0 0 1 1 0]


1    14
0    11
2     5
Name: count, dtype: int64

In [49]:
preds=model_gini.predict(x_train)
print(preds)
pd.Series(preds).value_counts()

[2 1 0 2 2 1 0 2 1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 1 2 1 2 1 0 2 1 1 1 1
 2 0 0 2 1 0 0 1 0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2
 2 0 0 0 1 1 0 0 1 0 2 1 2 1 0 1 0 2 0 0 2 0 2 1 1 1 2 2 1 2 0 1 2 2 0 1 1
 1 1 0 0 0 2 1 2 0]


2    44
0    39
1    37
Name: count, dtype: int64

In [51]:
pred=model_gini.predict(x_train)
np.mean(pred==y_train)

0.9666666666666667

In [55]:
pred=model_gini.predict(x_test)
np.mean(pred==y_test)

0.9666666666666667

In [56]:
pred=model_gini.predict(x_test)
np.median(pred==y_test)

1.0

In [58]:
pred=model_gini.predict(x_train)
np.median(pred==y_train)

1.0